[build]
  # Directorio público para servir archivos
  publish = "public"
  
  # No necesitamos comando de build para archivos estáticos
  command = "echo 'No build needed for static files'"

[build.environment]
  # Variables de entorno para el build (si las necesitas)
  NODE_ENV = "production"

# Configuración de redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers para seguridad y performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://back-adm.fly.dev"

# Cache para archivos estáticos
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers específicos para PWA
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0"
    Content-Type = "application/javascript"

# Headers para iconos PWA
[[headers]]
  for = "/icon-*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/png"

# Configuración para archivos específicos
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0"
