# fly.toml app configuration file generated for back-adm on 2025-08-24T12:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "back-adm"
primary_region = "gru"

[build]

[env]
  PORT = "8001"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[processes]
  app = "npm start"
